CREATE SEQUENCE SEQ_ALERTAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_ALERTAS (
  ID_ALERTA INTEGER DEFAULT SEQ_ALERTAS.NEXTVAL NOT NULL,
  ID_DESASTRE INTEGER NOT NULL,
  MENSAGEM VARCHAR2(500) NOT NULL,
  DATA DATE NOT NULL,
  LOCALIZACAO VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USUARIOS (
  ID_USUARIO INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL,
  NOME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL,
  TEL_SMS VARCHAR2(15) NOT NULL
);

CREATE SEQUENCE SEQ_DESASTRES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_DESASTRES (
  ID_DESASTRE INTEGER DEFAULT SEQ_DESASTRES.NEXTVAL NOT NULL,
  DESCRICAO VARCHAR2(255) NOT NULL,
  DATA DATE NOT NULL,
  NIVEL NUMBER(3) NOT NULL,
  TIPO NUMBER(1) NOT NULL
);